gcp_project = "visitor-counter-prod"
vc_api_service = "visitor-counter-api-0pb30vbmrig8i.apigateway.visitor-counter-prod.cloud.goog"
wif_repo = "principalSet://iam.googleapis.com/projects/860934251761/locations/global/workloadIdentityPools/counter-wi-pool/attribute.repository/CJ1138/visitor-counter"
gcp_creds = "visitor-counter-prod-094a3bc3714c.json"
backend = "donotuse-tf-backend"
api_config = "prod-config.yaml"