name: Push to GCR GitHub Action

on:
  push:
    branches:
    - dev

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.VC_QA_GCP_CREDS }}
          registry: gcr.io
          project_id: visitor-counter-qa
          image_name: visitor-counter
          image_tag: latest,v1
          dockerfile: ./docker/Dockerfile.qa
          context: ./docker