name: Deploy to Production

on:
  push:
    branches:
    - dev

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build_and_artifact:
    runs-on: ubuntu-latest
    steps:  
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
      
      - id: build
        name: Build container
        run: docker build . -t europe-west2-docker.pkg.dev/visitor-counter-qa/visitor-counter/visitor-counter:latest

      - id: auth_gcp
        name: Authorise with GCP project
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/300165146813/locations/global/workloadIdentityPools/counter-wi-pool/providers/github-provider'
          service_account: 'github-actions-runner@visitor-counter-qa.iam.gserviceaccount.com'

      - id: auth_artifact_registry
        name: Authorise with Artifact Registry
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - id: push
        name: Push to Artifact Registry
        run: docker push europe-west2-docker.pkg.dev/visitor-counter-qa/visitor-counter/visitor-counter

  deploy:
    needs: [build_and_artifact]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2

      - id: set_up_terraform
        name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - id: tf_init
        name: Terraform init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}

      - id: tf_apply
        name: Terraform apply
        run: terraform apply -auto-approve -input=false
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}
      
      - id: auth_gcp
        name: Authorise with GCP project
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/300165146813/locations/global/workloadIdentityPools/counter-wi-pool/providers/github-provider'
          service_account: 'github-actions-runner@visitor-counter-qa.iam.gserviceaccount.com'

      - id: setup-gcloud
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - id: update-cloud-run
        name: Update Cloud Run container
        run: gcloud run deploy visitor-counter --image europe-west2-docker.pkg.dev/visitor-counter-qa/visitor-counter/visitor-counter:latest 

 # test:
 #   runs-on: ubuntu-latest
 #   steps:
 #     - id: checkout
 #       name: Checkout repo
 #       uses: actions/checkout@v2