name: Deploy to Production

on:
  push:
    branches:
    - dev

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:  
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
      
      - id: build
        name: Build container
        run: docker build . -t europe-west2-docker.pkg.dev/visitor-counter-qa/visitor-counter/visitor-counter:latest

      - id: deploy
        name: Deploy to Artifact Registry
        run: docker push europe-west2-docker.pkg.dev/visitor-counter-qa/visitor-counter/visitor-counter

  deploy:
    needs: [build_and_deploy]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2

      - id: set_up_terraform
        name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - id: tf_init
        name: Terraform init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}

      - id: tf_plan
        name: Terraform plan
        run: terraform plan
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}

 # test:
 #   runs-on: ubuntu-latest
 #   steps:
 #     - id: checkout
 #       name: Checkout repo
 #       uses: actions/checkout@v2