name: Deploy to Production

on:
  push:
    branches:
    - dev

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  auth_with_gcp:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
        
      - id: auth
        name: Authorise with GCP project
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/300165146813/locations/global/workloadIdentityPools/counter-wi-pool/providers/github-provider'
          service_account: 'github-actions-runner@visitor-counter-qa.iam.gserviceaccount.com'

  tf_plan:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2

      - id: set_up_terraform
        name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - id: tf_init
        name: Terraform init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}

      - id: tf_plan
        name: Terraform plan
        run: terraform plan
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.VC_QA_GCP_CREDS }}